import Head from 'next/head'
import Header from '../components/Header'
import MiddleSection from '../components/MiddleSection'
import Navbar from '../components/Navbar'
import Sidebar from '../components/Sidebar'

export default function Home() {
  return (
    <div className="h-screen">
      <Head>
        <title>DashBoard</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <Navbar />
      <main className="flex h-screen top-0 sticky">
        <div className="w-[10%] xl:w-[5%] ">
        <Sidebar />
        </div>
        <div className="w-[90%] xl:w-[95%] overflow-scroll scrollbar-hide">
        <MiddleSection />
        </div>
      </main>
    
    </div>
  )
}
